name: SyncToGitee 
on: 
  workflow_dispatch:
  push:  # 代码提交时触发 
    branches: [ main ]
  schedule:  # 定时触发（可选）
    - cron: '0 0 * * *'
 
jobs:
  execute:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Script
        run: echo "000" > out.txt 
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        run: |
          git config --global user.name  "rtian002"
          git config --global user.email  "rtian002@gmail.com" 
          git add .
          git commit -m "Auto-commit by GitHub Actions"
          git push origin main 
