name: Sync to Repository 2 
on: [push]
jobs:
  sync:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
      - name: Push to abc 
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git remote origin https://rtian:$GITEE_TOKEN@gitee.com/rtian/abc.git  
          git push origin HEAD:master --force 
