name: SyncToGitee
on: 
 workflow_dispatch:
 push:  
  branches: main
 
jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4 
    - name: List file & Push to Gitee 
      env:
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      run: |
        git config --global user.name  "rtian"
        git config --global user.email  "rtian1@163.com" 
        git clone https://rtian:$GITEE_TOKEN@gitee.com/rtian/abc.git 
        cp 1 2 3 4 abc/
        cd abc
        git add .
        git commit -m "Sync from GitHub rtian002/abc"
        git push origin HEAD:master --force 
