name: Sync to Repository 2 
on: workflow_dispatch
#on: [push]
jobs:
  sync:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
      - name: List files
        run: |
          ls
